### ISSUE TITLE
when reference by a classlib and build with any cpu (vs 2019)

### ISSUE THREAD

**Issue by rdscfh** [NLua/KeraLua#65]
it will build with x64 lua54.dll

**Comment by viniciusjarina** [comment]
Please be more specific

**Comment by rdscfh** [comment]
an anycpu classlib default depens on a lua54.dll(x86)
when build with a classlib It build output with a x64 lua54.dll
when run with the classlib it show
System.BadImageFormatException: 试图加载格式不正确的程序。 (异常来自 HRESULT:0x8007000B)

**Comment by rdscfh** [comment]
dotnet framework 4.5

**Comment by viniciusjarina** [comment]
What are you trying to do? What are the repro steps?

**Comment by rdscfh** [comment]
.net framework4.5 classlib

`using NLua;

namespace luali
{
    public class Class1
    {
        public static void Run()
        {
            using(var lua=new Lua())
            {

            }
        }
    }
}`

.net framework4.5 Console app

`using luali;
using System;

namespace luan2
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Class1.Run();
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
            Console.Read();
        }
    }
}`

build and run
System.BadImageFormatException: 试图加载格式不正确的程序。 (异常来自 HRESULT:0x8007000B)
   在 KeraLua.NativeMethods.luaL_newstate()
   在 NLua.Lua..ctor()
   在 luali.Class1.Run() 位置 C:\Users\heyz\Desktop\luali\Class1.cs:行号 9
   在 luan2.Program.Main(String[] args) 位置 C:\Users\heyz\Desktop\luan\luan2\Program.cs:行号 12

**Comment by viniciusjarina** [comment]
The problem is because the NuGet target copies the x86 since the main program has the flag Preffer32 bit.
Try to uncheck that flag
[ConsoleApp2.zip](https://github.com/NLua/KeraLua/files/5009994/ConsoleApp2.zip)

**Comment by rdscfh** [comment]
i found that in the KeraLua.targets setting
```
<PropertyGroup>
        <!-- handle x86/x64 specifically -->
        <PreferredNativeLua Condition=" '$(PreferredNativeLua)' == '' and ( '$(PlatformTarget)' == 'x64' or '$(PlatformTarget)' == 'x86' ) ">$(PlatformTarget)</PreferredNativeLua> 
        <!-- handle Any CPU, considering Prefer32Bit -->
        <PreferredNativeLua Condition=" '$(PreferredNativeLua)' == '' and '$(Prefer32Bit)' == 'False' ">x64</PreferredNativeLua>  
        <PreferredNativeLua Condition=" '$(PreferredNativeLua)' == '' and '$(Prefer32Bit)' == 'True' ">x86</PreferredNativeLua> 
        <!-- fall back to x64 on 64-bit machines -->
        <PreferredNativeLua Condition=" '$(PreferredNativeLua)' == '' and $([System.Environment]::Is64BitOperatingSystem) ">x64</PreferredNativeLua> 
        <!-- fall back to x86 -->
        <PreferredNativeLua Condition=" '$(PreferredNativeLua)' == '' ">x86</PreferredNativeLua>
    </PropertyGroup>
```
but a classlib can never set the flag  Preffer32 bit.

**Comment by viniciusjarina** [comment]
Change the Prefer32Bit flag from your final .exe 😉

**Comment by viniciusjarina** [comment]
Let me try to explain what is happening:

When you run a AnyCPU assemply that contains the flag Prefer32 bit the CLR may or may not run your application as x64.
In your case when you reference a class library (AnyCPU) CLR is loading your application as x64.

The way that the .targets works, will copy the x64 version if the flag Prefer32 is not set.

There a couple of options you can workaround this:

* You can move your assemblies to a specific target e.g x64
* You can remove the flag Prefer32bits and the .targets will copy the x64 bit
* You can p/Invoke [SetDllDirectory](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setdlldirectorya) and specify the directory you want to load the DLL depending if you are running x86 or x64 (Some binding libraries do this, but I don't think is a good idea since that afect the whole process I guess is up to the user if they want to change the DLL directory search.

I hope this help you thank you.
